config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static#index'
  resources :exercises do
    member do
      resources :exercise_steps
    end
  end
  resources :equipment
  resources :units

  namespace :telegram do
    get "/programs" => 'telegram_api1#programs'
    get "/details" => 'telegram_api1#details'
    get "sign" => 'telegram_api1#sign'
    get "/unsign" => 'telegram_api1#unsign'
    get "/mysigns" => 'telegram_api1#mysigns'
    get "/today" => 'telegram_api1#today'
    get "/day" => 'telegram_api1#day'
    get "schedule" => 'telegram_api1#schedule'
  end

  resources :programs
  resources :program_days
  resources :day_exercises

  post "api/update_order" => 'api#update_order'
  post "api/clone_program_day" => 'api#clone_program_day'

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  has_and_belongs_to_many :exercises
  validates :title, presence: true
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController

  before_action :set_chapter
  before_action :get_item, only: [:show, :edit, :destroy, :update]

  def index
    @items = Equipment.all
  end

  def create
    @item = Equipment.new(equipment_params)
    if @item.save
      redirect_to equipment_index_path, notice: 'Создано'
    else
      render action: 'new', error: 'Ошибка при добавлении'
    end
  end

  def edit
    @chapters.push({title: "Редактировать \"#{@item.title}\"", src: "#"})
  end

  def update
    if @item.update(equipment_params)
      redirect_to edit_equipment_path(@item), notice: 'Сохранено'
    else
      render action: 'edit', error: 'Ошибка сохранения'
    end
  end

  def new
    @item = Equipment.new
    @chapters.push({title: "Добавить инвентарь", src: "#"})
  end

  def destroy
    if @item.destroy
      redirect_to equipment_index_path(@item), notice: 'Удалено'
    else
      render action: 'edit', error: 'Ошибка удаления'
    end
  end

  def set_chapter
    @chapters = [{title: 'Ед. изм.', src: equipment_index_path}]
  end

  private

  def equipment_params
    params[:equipment].permit( :title, :description )
  end

  def get_item
    @item = Equipment.find(params[:id])
  end

end

app/views/equipment/_form.html.slim
.row
  .col.s12
    = form_for(@item) do |f|


      .row
        .col.s12
          .input-field
            = f.text_field :title
            label for='title' Наименование

      .row
        .col.s12
          .input-field
            = f.text_area :description, class: 'materialize-textarea'
            label for='description' Описание

      .row
        .col.s7
          .input-field
            button.btn.waves-effect.waves-light name="action" type="submit"
              | Сохранить
              i.material-icons.right send
            a.btn-flat href="#{equipment_index_path}" Отмена
        - unless @item.new_record?
          .col.s5
            .input-field
              =link_to 'Удалить', equipment_path(@item), method: :delete, class: 'btn waves-effect right waves-light red lighten-2', data: {confirm: 'Подтвердите удаление'}

app/views/equipment/edit.html.slim
= render partial: 'equipment/form'

app/views/equipment/index.html.slim
.row
  .col.s9
    h5.header Инвентарь
  .col.s3
    a.btn.waves-effect.top10.waves-light href=new_equipment_path Cоздать
ul
  - @items.each do |item  |
    li: a href=edit_equipment_path(item) = item.title

app/views/equipment/new.html.slim
= render partial: 'equipment/form'