config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static#index'
  resources :exercises do
    member do
      resources :exercise_steps
    end
  end
  resources :equipment
  resources :units

  namespace :telegram do
    get "/programs" => 'telegram_api1#programs'
    get "/details" => 'telegram_api1#details'
    get "sign" => 'telegram_api1#sign'
    get "/unsign" => 'telegram_api1#unsign'
    get "/mysigns" => 'telegram_api1#mysigns'
    get "/today" => 'telegram_api1#today'
    get "/day" => 'telegram_api1#day'
    get "schedule" => 'telegram_api1#schedule'
  end

  resources :programs
  resources :program_days
  resources :day_exercises

  post "api/update_order" => 'api#update_order'
  post "api/clone_program_day" => 'api#clone_program_day'

end

app/models/program.rb
class Program < ActiveRecord::Base
  validates :title, presence: true
  has_many :program_days
  has_many :subscriptions
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  
  before_action :set_chapter
  before_action :get_item, only: [:show, :edit, :destroy, :update]

  def index
    @items = Program.includes(:subscriptions)
  end

  def create
    @item = Program.new(program_params)
    if @item.save
      if params[:days_count].present?
        params[:days_count].to_i.times do |day|
          @item.program_days.create({order: day+1})
        end
      end
      redirect_to programs_path, notice: 'Создано'
    else
      render action: 'new', error: 'Ошибка при добавлении'
    end
  end

  def edit
    @days = @item.program_days.order('program_days.order ASC').to_a
    @program_days_json = @days.map do |day|
      day.as_indexed_json.values[0]
    end.to_json

    @chapters.push({title: "Редактировать \"#{@item.title}\"", src: "#"})
  end

  def update
    if @item.update(program_params)
      redirect_to edit_program_path(@item), notice: 'Сохранено'
    else
      render action: 'edit', error: 'Ошибка сохранения'
    end
  end

  def new
    @item = Program.new
    @chapters.push({title: "Добавить программу", src: "#"})
  end

  def destroy
    if @item.destroy
      redirect_to programs_path(@item), notice: 'Удалено'
    else
      render action: 'edit', error: 'Ошибка удаления'
    end
  end

  def set_chapter
    @chapters = [{title: 'Программы', src: programs_path}]
  end

  private

  def program_params
    params[:program].permit(:title, :description, :cycle)
  end

  def get_item
    @item = Program.find(params[:id])
  end
  
  
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_day_short.html.slim
- if day.day_exercises.any?

- else
  p Нет описания

a.day-edit-link href=edit_program_day_path(day) Редактировать

app/views/programs/_form.html.slim
.row
  ul.tabs.z-depth-1
    li.tab
      a.active href="#common"  Общая
    - disabled = 'disabled' if @item.new_record?
    li.tab class=disabled
      a href="#days"  Расписание

  #common.top30
    .row
      .col.s12
        = form_for(@item) do |f|
          .row
            .col.s12
              .input-field
                = f.text_field :title
                label for='program_title' Название

          .row
            .col.s12
              .input-field
                = f.text_area :description, class: 'materialize-textarea'
                label for='program_description' Описание

          .row

            .input-field
              = f.check_box :cycle
              label for='program_cycle' Повторять по кругу

          - if @item.new_record?
            .row
              .col.s12
                .input-field
                  = text_field_tag :days_count
                  label for='program_days_count' Сколько дней создать?

          .row
            .col.s7
              .input-field
                button.btn.waves-effect.waves-light name="action" type="submit"
                  | Сохранить
                  i.material-icons.right send
                a.btn-flat href="#{programs_path}" Отмена
            - unless @item.new_record?
              .col.s5
                .input-field
                  =link_to 'Удалить', program_path(@item), method: :delete, class: 'btn waves-effect right waves-light red lighten-2', data: {confirm: 'Подтвердите удаление'}

  - if !@item.new_record?
    #days.top30
      .row
        ul.col.s12.days-list.uisortable data-url=api_update_order_path({class: 'ProgramDay'})

javascript:
 window.program_days = #{@program_days_json.try(:html_safe)};
 window.parent_id = #{@item.id};

app/views/programs/edit.html.slim
= render partial: 'programs/form'

app/views/programs/index.html.slim
.row
  .col.s6
    h5.header Программы
  .col.s6
    a.btn.waves-effect.top10.right.waves-light href=new_program_path Cоздать
ul
  - @items.each do |item|
    li: a href=edit_program_path(item) #{item.title} (#{item.subscriptions.count})

app/views/programs/new.html.slim
= render partial: 'programs/form'