config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static#index'
  resources :exercises do
    member do
      resources :exercise_steps
    end
  end
  resources :equipment
  resources :units

  namespace :telegram do
    get "/programs" => 'telegram_api1#programs'
    get "/details" => 'telegram_api1#details'
    get "sign" => 'telegram_api1#sign'
    get "/unsign" => 'telegram_api1#unsign'
    get "/mysigns" => 'telegram_api1#mysigns'
    get "/today" => 'telegram_api1#today'
    get "/day" => 'telegram_api1#day'
    get "schedule" => 'telegram_api1#schedule'
  end

  resources :programs
  resources :program_days
  resources :day_exercises

  post "api/update_order" => 'api#update_order'
  post "api/clone_program_day" => 'api#clone_program_day'

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  
    before_action :set_chapter
    before_action :get_item, only: [:show, :edit, :destroy, :update]

    def index
      @items = Unit.all
    end

    def create
      @item = Unit.new(unit_params)
      if @item.save
        redirect_to units_path, notice: 'Создано'
      else
        render action: 'new', error: 'Ошибка при добавлении'
      end
    end

    def edit
      @chapters.push({title: "Редактировать \"#{@item.title}\"", src: "#"})
    end

    def update
      if @item.update(unit_params)
        redirect_to edit_unit_path(@item), notice: 'Сохранено'
      else
        render action: 'edit', error: 'Ошибка сохранения'
      end
    end

    def new
      @item = Unit.new
      @chapters.push({title: "Добавить ед.изм", src: "#"})
    end

    def destroy
      if @item.destroy
        redirect_to units_path(@item), notice: 'Удалено'
      else
        render action: 'edit', error: 'Ошибка удаления'
      end
    end

    def set_chapter
      @chapters = [{title: 'Ед. изм.', src: units_path}]
    end

    private

    def unit_params
      params[:unit].permit(:title, :short_title, :few_title, :many_title)
    end

    def get_item
      @item = Unit.find(params[:id])
    end
    
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.slim
.row
  .col.s12
    = form_for(@item) do |f|
      .row
        .col.s12
          .input-field
            = f.text_field :short_title
            label for='short_title' Сокращенное наименование

      .row
        .col.s12
          .input-field
            = f.text_field :title
            label for='title' Один

      .row
        .col.s12
          .input-field
            = f.text_field :few_title
            label for='few_title' Два

      .row
        .col.s12
          .input-field
            = f.text_field :many_title
            label for='many_title' Много

      .row
        .col.s7
          .input-field
            button.btn.waves-effect.waves-light name="action" type="submit"
              | Сохранить
              i.material-icons.right send
            a.btn-flat href="#{units_path}" Отмена
        - unless @item.new_record?
          .col.s5
            .input-field
              =link_to 'Удалить', unit_path(@item), method: :delete, class: 'btn waves-effect right waves-light red lighten-2', data: {confirm: 'Подтвердите удаление'}

app/views/units/edit.html.slim
= render partial: 'units/form'

app/views/units/index.html.slim
.row
  .col.s8
    h5.header Единицы измерения
  .col.s4
    a.btn.waves-effect.top10.right.waves-light href=new_unit_path Cоздать
ul
  - @items.each do |item  |
    li: a href=edit_unit_path(item) = item.title

app/views/units/new.html.slim
= render partial: 'units/form'